backend:
  name: github
  repo: dealovadealova/blog-islami
  branch: main
  
media_folder: "images"
public_folder: "/images"

collections:
  - name: "artikel"
    label: "Artikel Kajian"
    folder: "artikel"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Judul", name: "title", widget: "string"}
      - label: "Kategori"
        name: "kategori"
        widget: "select"
        options: ["Akhlak", "Motivasi", "Inspirasi", "Kisah", "Renungan", "Hikmah", "True Story"]
      - {label: "Tanggal", name: "date", widget: "datetime"}
      - {label: "Gambar Ilustrasi", name: "thumbnail", widget: "image", required: false}
      - {label: "Ringkasan", name: "summary", widget: "text"}
      - {label: "Isi Tulisan", name: "body", widget: "markdown"}
